import type {
	EffectPresetCatalog,
	EffectPresetSelectionState,
	PaletteSwatch,
	PresetCatalog,
	PresetSelectionState,
	ShapeOption,
	StudioSettings,
} from '@/components/gradient-studio/types';

function paletteFromHexes(hexes: string[]): PaletteSwatch[] {
	const even = hexes.length > 0 ? 1 / hexes.length : 1;
	return hexes.map((hex, index) => ({
		id: `palette-${index + 1}`,
		hex,
		weight: even,
		enabled: true,
		locked: false,
	}));
}

export const SHAPE_OPTIONS: ShapeOption[] = [
	{
		label: 'Circle',
		value: 'circle',
		help: 'Classic soft orb forms.',
	},
	{
		label: 'Organic Blob',
		value: 'abstract-curved',
		help: 'Soft fluid blob-like shapes.',
	},
];

const BASE_PALETTE = paletteFromHexes([
	'#0ea5e9',
	'#38bdf8',
	'#67e8f9',
	'#fde68a',
	'#f97316',
]);

export const DEFAULT_STUDIO_SETTINGS: StudioSettings = {
	circleCount: 15,
	minRadius: 92,
	maxRadius: 456,
	allowCrop: true,
	shapeSelections: SHAPE_OPTIONS.map((shape) => shape.value),
	shapeSpeedMin: 0.7,
	shapeSpeedMax: 1.35,
	animate: true,
	animationSpeed: 1,
	movementIntensity: 1,
	scaleIntensity: 1,
	blurEnabled: true,
	blurStdDeviation: 72,
	glowEnabled: false,
	glowStdDeviation: 105,
	glowIntensity: 2.8,
	glowBlendMode: 'screen',
	noiseEnabled: true,
	noiseOpacity: 0.06,
	noiseFrequency: 0.95,
	coarseNoiseOpacity: 0.03,
	coarseNoiseFrequency: 0.08,
	warpEnabled: false,
	warpAmount: 14,
	warpSpeed: 0.45,
	warpBaseFrequency: 0.004,
	metaballEnabled: false,
	metaballBlur: 20,
	metaballThreshold: 0.62,
	bloomEnabled: false,
	bloomThreshold: 0.62,
	bloomRadius: 34,
	bloomIntensity: 0.58,
	posterizeEnabled: false,
	posterizeLevels: 5,
	posterizeOpacity: 0.28,
	causticEnabled: false,
	causticIntensity: 0.22,
	causticScale: 0.016,
	causticSpeed: 0.42,
	depthEnabled: true,
	depthLayers: 3,
	depthStrength: 0.5,
	vignetteEnabled: true,
	vignetteAmount: 0.2,
	vignetteColor: '#040a16',
	fringeEnabled: false,
	fringeAmount: 1.1,
	sweepEnabled: false,
	sweepIntensity: 0.16,
	sweepWidth: 0.22,
	sweepSpeed: 0.45,
	sweepAngle: -24,
	paletteDriftEnabled: false,
	paletteDriftSpeed: 0.22,
	hueRotateEnabled: false,
	hueRotateDegrees: 22,
	hueRotateSpeed: 0.3,
	seed: 'studio-default-seed',
	seedLocked: true,
	palette: BASE_PALETTE,
	backgroundColor: '#020617',
};

export const PRESET_CATALOG: PresetCatalog = {
	style: [
		{
			key: 'style-bloom-atmosphere',
			label: 'Bloom Atmosphere',
			description:
				'Soft cinematic bloom and glow with large atmospheric forms.',
			patch: {
				circleCount: 18,
				minRadius: 150,
				maxRadius: 700,
				allowCrop: true,
				shapeSelections: ['circle', 'abstract-curved'],
				animate: true,
				animationSpeed: 0.75,
				movementIntensity: 0.55,
				scaleIntensity: 0.45,
				shapeSpeedMin: 0.4,
				shapeSpeedMax: 1.0,
				blurEnabled: true,
				blurStdDeviation: 130,
				glowEnabled: true,
				glowStdDeviation: 150,
				glowIntensity: 3.5,
				glowBlendMode: 'screen',
				noiseEnabled: true,
				noiseOpacity: 0.03,
				noiseFrequency: 0.85,
				coarseNoiseOpacity: 0.01,
				coarseNoiseFrequency: 0.05,
				warpEnabled: false,
				metaballEnabled: false,
				bloomEnabled: true,
				bloomThreshold: 0.52,
				bloomRadius: 70,
				bloomIntensity: 1.18,
				posterizeEnabled: false,
				causticEnabled: false,
				depthEnabled: true,
				depthLayers: 3,
				depthStrength: 0.5,
				vignetteEnabled: true,
				vignetteAmount: 0.2,
				vignetteColor: '#040a16',
				fringeEnabled: false,
				sweepEnabled: false,
				paletteDriftEnabled: false,
				hueRotateEnabled: false,
			},
		},
		{
			key: 'style-poster-punch',
			label: 'Poster Punch',
			description: 'Hard posterized graphic look with minimal blending.',
			patch: {
				circleCount: 14,
				minRadius: 120,
				maxRadius: 620,
				allowCrop: false,
				shapeSelections: ['circle', 'abstract-curved'],
				animate: false,
				animationSpeed: 1,
				movementIntensity: 0,
				scaleIntensity: 0,
				shapeSpeedMin: 0.7,
				shapeSpeedMax: 1.35,
				blurEnabled: false,
				glowEnabled: false,
				noiseEnabled: false,
				warpEnabled: false,
				metaballEnabled: false,
				bloomEnabled: false,
				posterizeEnabled: true,
				posterizeLevels: 3,
				posterizeOpacity: 0.86,
				causticEnabled: false,
				depthEnabled: false,
				vignetteEnabled: false,
				fringeEnabled: true,
				fringeAmount: 4.2,
				sweepEnabled: false,
				paletteDriftEnabled: false,
				hueRotateEnabled: false,
			},
		},
		{
			key: 'style-prism-fringe',
			label: 'Prism Fringe',
			description: 'Chromatic edge split with sweep light and crisp contrast.',
			patch: {
				circleCount: 20,
				minRadius: 96,
				maxRadius: 560,
				allowCrop: true,
				shapeSelections: ['circle', 'abstract-curved'],
				animate: true,
				animationSpeed: 1.2,
				movementIntensity: 1.1,
				scaleIntensity: 0.95,
				shapeSpeedMin: 0.8,
				shapeSpeedMax: 1.9,
				blurEnabled: true,
				blurStdDeviation: 78,
				glowEnabled: true,
				glowStdDeviation: 118,
				glowIntensity: 2.8,
				glowBlendMode: 'color-dodge',
				noiseEnabled: true,
				noiseOpacity: 0.05,
				noiseFrequency: 1.22,
				coarseNoiseOpacity: 0.045,
				coarseNoiseFrequency: 0.11,
				warpEnabled: false,
				metaballEnabled: false,
				bloomEnabled: true,
				bloomThreshold: 0.58,
				bloomRadius: 40,
				bloomIntensity: 0.72,
				posterizeEnabled: false,
				causticEnabled: false,
				depthEnabled: true,
				depthLayers: 4,
				depthStrength: 0.8,
				vignetteEnabled: true,
				vignetteAmount: 0.16,
				vignetteColor: '#020511',
				fringeEnabled: true,
				fringeAmount: 4.8,
				sweepEnabled: true,
				sweepIntensity: 0.36,
				sweepWidth: 0.16,
				sweepSpeed: 1.1,
				sweepAngle: -30,
				paletteDriftEnabled: false,
				hueRotateEnabled: false,
			},
		},
		{
			key: 'style-liquid-warp',
			label: 'Liquid Warp',
			description:
				'Fluid distortion with metaball fusion and refractive texture.',
			patch: {
				circleCount: 22,
				minRadius: 120,
				maxRadius: 660,
				allowCrop: true,
				shapeSelections: ['circle', 'abstract-curved'],
				animate: true,
				animationSpeed: 1.1,
				movementIntensity: 1.05,
				scaleIntensity: 0.92,
				shapeSpeedMin: 0.7,
				shapeSpeedMax: 1.6,
				blurEnabled: true,
				blurStdDeviation: 104,
				glowEnabled: true,
				glowStdDeviation: 92,
				glowIntensity: 2.1,
				glowBlendMode: 'overlay',
				noiseEnabled: true,
				noiseOpacity: 0.04,
				noiseFrequency: 1.02,
				coarseNoiseOpacity: 0.018,
				coarseNoiseFrequency: 0.06,
				warpEnabled: true,
				warpAmount: 28,
				warpSpeed: 0.96,
				warpBaseFrequency: 0.007,
				metaballEnabled: true,
				metaballBlur: 30,
				metaballThreshold: 0.56,
				bloomEnabled: true,
				bloomThreshold: 0.62,
				bloomRadius: 34,
				bloomIntensity: 0.58,
				posterizeEnabled: false,
				causticEnabled: true,
				causticIntensity: 0.34,
				causticScale: 0.011,
				causticSpeed: 0.95,
				depthEnabled: true,
				depthLayers: 4,
				depthStrength: 0.86,
				vignetteEnabled: true,
				vignetteAmount: 0.24,
				vignetteColor: '#020612',
				fringeEnabled: false,
				sweepEnabled: true,
				sweepIntensity: 0.18,
				sweepWidth: 0.25,
				sweepSpeed: 0.6,
				sweepAngle: -22,
				paletteDriftEnabled: false,
				hueRotateEnabled: false,
			},
		},
		{
			key: 'style-editorial-grain',
			label: 'Editorial Grain',
			description:
				'Moody print-style grain with restrained motion and deep vignette.',
			patch: {
				circleCount: 16,
				minRadius: 150,
				maxRadius: 720,
				allowCrop: false,
				shapeSelections: ['circle', 'abstract-curved'],
				animate: true,
				animationSpeed: 0.32,
				movementIntensity: 0.2,
				scaleIntensity: 0.1,
				shapeSpeedMin: 0.18,
				shapeSpeedMax: 0.45,
				blurEnabled: true,
				blurStdDeviation: 118,
				glowEnabled: false,
				noiseEnabled: true,
				noiseOpacity: 0.17,
				noiseFrequency: 1.3,
				coarseNoiseOpacity: 0.11,
				coarseNoiseFrequency: 0.22,
				warpEnabled: false,
				metaballEnabled: false,
				bloomEnabled: false,
				posterizeEnabled: true,
				posterizeLevels: 5,
				posterizeOpacity: 0.32,
				causticEnabled: false,
				depthEnabled: true,
				depthLayers: 2,
				depthStrength: 0.28,
				vignetteEnabled: true,
				vignetteAmount: 0.5,
				vignetteColor: '#000000',
				fringeEnabled: false,
				sweepEnabled: false,
				paletteDriftEnabled: false,
				hueRotateEnabled: false,
			},
		},
		{
			key: 'style-caustic-glass',
			label: 'Caustic Glass',
			description:
				'Energetic glassy lighting with caustics, sweep, and bold depth.',
			patch: {
				circleCount: 24,
				minRadius: 110,
				maxRadius: 680,
				allowCrop: true,
				shapeSelections: ['circle', 'abstract-curved'],
				animate: true,
				animationSpeed: 1.35,
				movementIntensity: 1.25,
				scaleIntensity: 1.08,
				shapeSpeedMin: 0.9,
				shapeSpeedMax: 2.0,
				blurEnabled: true,
				blurStdDeviation: 88,
				glowEnabled: true,
				glowStdDeviation: 126,
				glowIntensity: 3.2,
				glowBlendMode: 'overlay',
				noiseEnabled: true,
				noiseOpacity: 0.045,
				noiseFrequency: 1.1,
				coarseNoiseOpacity: 0.024,
				coarseNoiseFrequency: 0.08,
				warpEnabled: true,
				warpAmount: 18,
				warpSpeed: 0.72,
				warpBaseFrequency: 0.005,
				metaballEnabled: false,
				bloomEnabled: true,
				bloomThreshold: 0.48,
				bloomRadius: 58,
				bloomIntensity: 0.95,
				posterizeEnabled: false,
				causticEnabled: true,
				causticIntensity: 0.55,
				causticScale: 0.008,
				causticSpeed: 1.45,
				depthEnabled: true,
				depthLayers: 5,
				depthStrength: 1.05,
				vignetteEnabled: true,
				vignetteAmount: 0.22,
				vignetteColor: '#050914',
				fringeEnabled: true,
				fringeAmount: 3.8,
				sweepEnabled: true,
				sweepIntensity: 0.28,
				sweepWidth: 0.2,
				sweepSpeed: 0.9,
				sweepAngle: -35,
				paletteDriftEnabled: true,
				paletteDriftSpeed: 0.18,
				hueRotateEnabled: false,
			},
		},
	],
	layout: [
		{
			key: 'layout-wide',
			label: 'Wide Wash',
			description: 'Large forms with relaxed composition.',
			patch: {
				circleCount: 20,
				minRadius: 180,
				maxRadius: 740,
				allowCrop: true,
			},
		},
		{
			key: 'layout-dense',
			label: 'Layer Rich',
			description:
				'Maximum overlap while staying within the 10-30 shape range.',
			patch: {
				circleCount: 30,
				minRadius: 78,
				maxRadius: 320,
				allowCrop: true,
			},
		},
		{
			key: 'layout-centered',
			label: 'Center Focus',
			description: 'Compact interior-focused compositions.',
			patch: {
				circleCount: 18,
				minRadius: 130,
				maxRadius: 440,
				allowCrop: false,
			},
		},
		{
			key: 'layout-geometry',
			label: 'Geometric Board',
			description: 'Shape-forward scene with harder primitives.',
			patch: {
				shapeSelections: ['circle', 'abstract-curved'],
				circleCount: 24,
				minRadius: 110,
				maxRadius: 380,
			},
		},
	],
	motion: [
		{
			key: 'motion-off',
			label: 'Off',
			description: 'Disable animation and hold a still frame.',
			patch: {
				animate: false,
			},
		},
		{
			key: 'motion-calm',
			label: 'Calm Drift',
			description: 'Low velocity for soft ambient motion.',
			patch: {
				animate: true,
				animationSpeed: 0.55,
				movementIntensity: 0.42,
				scaleIntensity: 0.34,
				shapeSpeedMin: 0.35,
				shapeSpeedMax: 0.9,
			},
		},
		{
			key: 'motion-balanced',
			label: 'Balanced Float',
			description: 'Default production-safe tempo.',
			patch: {
				animate: true,
				animationSpeed: 1,
				movementIntensity: 1,
				scaleIntensity: 1,
				shapeSpeedMin: 0.7,
				shapeSpeedMax: 1.35,
			},
		},
		{
			key: 'motion-high',
			label: 'High Energy',
			description: 'Fast and expressive movement profile.',
			patch: {
				animate: true,
				animationSpeed: 1.52,
				movementIntensity: 1.42,
				scaleIntensity: 1.26,
				shapeSpeedMin: 1.08,
				shapeSpeedMax: 2.1,
			},
		},
	],
	palette: [
		{
			key: 'palette-none',
			label: 'Off',
			description:
				'Keep current manual colors without applying a palette preset.',
			patch: {},
		},
		{
			key: 'palette-cyan-amber',
			label: 'Cyan + Amber',
			description: 'Balanced cool/warm modern palette.',
			patch: {
				backgroundColor: '#06b6d4',
				palette: paletteFromHexes([
					'#06b6d4',
					'#22d3ee',
					'#67e8f9',
					'#fbbf24',
					'#f97316',
				]),
			},
		},
		{
			key: 'palette-ocean',
			label: 'Ocean',
			description: 'Deep water blues and aqua tones.',
			patch: {
				backgroundColor: '#1e3a8a',
				palette: paletteFromHexes([
					'#1e3a8a',
					'#1d4ed8',
					'#0284c7',
					'#22d3ee',
					'#ecfeff',
				]),
			},
		},
		{
			key: 'palette-flare',
			label: 'Solar Flare',
			description: 'Bright warm tones for energetic visuals.',
			patch: {
				backgroundColor: '#b91c1c',
				palette: paletteFromHexes([
					'#b91c1c',
					'#ef4444',
					'#f97316',
					'#fbbf24',
					'#fef3c7',
				]),
			},
		},
		{
			key: 'palette-forest',
			label: 'Forest Mist',
			description: 'Natural greens and dark contrast.',
			patch: {
				backgroundColor: '#14532d',
				palette: paletteFromHexes([
					'#14532d',
					'#15803d',
					'#4ade80',
					'#bbf7d0',
					'#052e16',
				]),
			},
		},
		{
			key: 'palette-neon',
			label: 'Neon Pop',
			description: 'High saturation stylized palette.',
			patch: {
				backgroundColor: '#06b6d4',
				palette: paletteFromHexes([
					'#06b6d4',
					'#22d3ee',
					'#f43f5e',
					'#f59e0b',
					'#84cc16',
				]),
			},
		},
		{
			key: 'palette-aurora-night',
			label: 'Aurora Night',
			description: 'Deep night blues with electric aurora accents.',
			patch: {
				backgroundColor: '#0b1026',
				palette: paletteFromHexes([
					'#0b1026',
					'#1d4ed8',
					'#2563eb',
					'#14b8a6',
					'#a78bfa',
				]),
			},
		},
		{
			key: 'palette-lava-lux',
			label: 'Lava Lux',
			description: 'Hot ember oranges with bright gold and ember pink.',
			patch: {
				backgroundColor: '#7f1d1d',
				palette: paletteFromHexes([
					'#7f1d1d',
					'#dc2626',
					'#f97316',
					'#facc15',
					'#fb7185',
				]),
			},
		},
		{
			key: 'palette-desert-dusk',
			label: 'Desert Dusk',
			description: 'Muted warm earth tones with dusk violet contrast.',
			patch: {
				backgroundColor: '#7c2d12',
				palette: paletteFromHexes([
					'#7c2d12',
					'#c2410c',
					'#f59e0b',
					'#fde68a',
					'#7e22ce',
				]),
			},
		},
		{
			key: 'palette-glacier',
			label: 'Glacier Fade',
			description: 'Cold arctic whites and frosted blue gradients.',
			patch: {
				backgroundColor: '#ecfeff',
				palette: paletteFromHexes([
					'#ecfeff',
					'#cffafe',
					'#a5f3fc',
					'#38bdf8',
					'#0c4a6e',
				]),
			},
		},
		{
			key: 'palette-rose-garden',
			label: 'Rose Garden',
			description: 'Soft florals with warm petals and fresh green accents.',
			patch: {
				backgroundColor: '#fbcfe8',
				palette: paletteFromHexes([
					'#fbcfe8',
					'#f472b6',
					'#fb7185',
					'#fde68a',
					'#4ade80',
				]),
			},
		},
		{
			key: 'palette-synthwave',
			label: 'Synthwave',
			description: 'Retro magenta, electric blue, and sunset orange.',
			patch: {
				backgroundColor: '#312e81',
				palette: paletteFromHexes([
					'#312e81',
					'#4338ca',
					'#a855f7',
					'#f43f5e',
					'#fb923c',
				]),
			},
		},
		{
			key: 'palette-citrus-punch',
			label: 'Citrus Punch',
			description: 'Lime and citrus tones with high-energy warm accents.',
			patch: {
				backgroundColor: '#14532d',
				palette: paletteFromHexes([
					'#14532d',
					'#84cc16',
					'#facc15',
					'#fb923c',
					'#dc2626',
				]),
			},
		},
		{
			key: 'palette-ink-cream',
			label: 'Ink and Cream',
			description: 'Editorial neutrals from deep ink to warm paper cream.',
			patch: {
				backgroundColor: '#020617',
				palette: paletteFromHexes([
					'#020617',
					'#334155',
					'#94a3b8',
					'#e2e8f0',
					'#fff7ed',
				]),
			},
		},
		{
			key: 'palette-candy-pop',
			label: 'Candy Pop',
			description:
				'Playful high-saturation pink, orange, yellow, and cyan blend.',
			patch: {
				backgroundColor: '#ec4899',
				palette: paletteFromHexes([
					'#ec4899',
					'#fb7185',
					'#f97316',
					'#facc15',
					'#22d3ee',
				]),
			},
		},
		{
			key: 'palette-midnight-mint',
			label: 'Midnight Mint',
			description: 'Dark midnight base with cool mint transitions.',
			patch: {
				backgroundColor: '#020617',
				palette: paletteFromHexes([
					'#020617',
					'#0f172a',
					'#0f766e',
					'#14b8a6',
					'#99f6e4',
				]),
			},
		},
		{
			key: 'palette-volcanic-ash',
			label: 'Volcanic Ash',
			description: 'Smoky charcoals with ember reds and glowing orange.',
			patch: {
				backgroundColor: '#111827',
				palette: paletteFromHexes([
					'#111827',
					'#374151',
					'#7f1d1d',
					'#dc2626',
					'#f97316',
				]),
			},
		},
		{
			key: 'palette-arctic-pastel',
			label: 'Arctic Pastel',
			description: 'Icy pastels with soft blue and pink accents.',
			patch: {
				backgroundColor: '#e0f2fe',
				palette: paletteFromHexes([
					'#e0f2fe',
					'#bae6fd',
					'#a5b4fc',
					'#fbcfe8',
					'#f0f9ff',
				]),
			},
		},
		{
			key: 'palette-rainforest-deep',
			label: 'Rainforest Deep',
			description: 'Dense jungle greens with moss and dark canopy contrast.',
			patch: {
				backgroundColor: '#052e16',
				palette: paletteFromHexes([
					'#052e16',
					'#14532d',
					'#166534',
					'#4d7c0f',
					'#bbf7d0',
				]),
			},
		},
		{
			key: 'palette-retro-arcade',
			label: 'Retro Arcade',
			description: 'Electric magenta, cyan, and yellow with deep violet base.',
			patch: {
				backgroundColor: '#1e1b4b',
				palette: paletteFromHexes([
					'#1e1b4b',
					'#7c3aed',
					'#ec4899',
					'#22d3ee',
					'#fde047',
				]),
			},
		},
		{
			key: 'palette-lilac-dream',
			label: 'Lilac Dream',
			description: 'Lavender gradients with rosy and sky highlights.',
			patch: {
				backgroundColor: '#312e81',
				palette: paletteFromHexes([
					'#312e81',
					'#6366f1',
					'#a78bfa',
					'#f5d0fe',
					'#bae6fd',
				]),
			},
		},
		{
			key: 'palette-royal-gold',
			label: 'Royal Gold',
			description: 'Navy and royal blues balanced with rich gold highlights.',
			patch: {
				backgroundColor: '#0f172a',
				palette: paletteFromHexes([
					'#0f172a',
					'#1d4ed8',
					'#1e40af',
					'#f59e0b',
					'#fef3c7',
				]),
			},
		},
		{
			key: 'palette-coastal-sunrise',
			label: 'Coastal Sunrise',
			description: 'Sea blue mixed with coral sunrise tones.',
			patch: {
				backgroundColor: '#0c4a6e',
				palette: paletteFromHexes([
					'#0c4a6e',
					'#0284c7',
					'#22d3ee',
					'#fb7185',
					'#fdba74',
				]),
			},
		},
		{
			key: 'palette-copper-oxide',
			label: 'Copper Oxide',
			description: 'Weathered copper oranges and teal patina contrast.',
			patch: {
				backgroundColor: '#7c2d12',
				palette: paletteFromHexes([
					'#7c2d12',
					'#c2410c',
					'#ea580c',
					'#0f766e',
					'#99f6e4',
				]),
			},
		},
		{
			key: 'palette-gray',
			label: 'Slate Mono',
			description: 'Neutral minimalist grayscale.',
			patch: {
				backgroundColor: '#f8fafc',
				palette: paletteFromHexes([
					'#f8fafc',
					'#94a3b8',
					'#64748b',
					'#334155',
					'#0f172a',
				]),
			},
		},
	],
	seed: [
		{
			key: 'seed-studio',
			label: 'Studio Stable',
			description: 'Predictable baseline composition.',
			patch: {
				seed: 'studio-stable',
				seedLocked: true,
			},
		},
		{
			key: 'seed-wave',
			label: 'Wave Grid',
			description: 'Evenly distributed soft rhythm.',
			patch: {
				seed: 'wave-grid',
				seedLocked: true,
			},
		},
		{
			key: 'seed-chaos',
			label: 'Chaos Bloom',
			description: 'Higher variance composition.',
			patch: {
				seed: 'chaos-bloom',
				seedLocked: true,
			},
		},
		{
			key: 'seed-grid',
			label: 'Grid Drift',
			description: 'Structured look with depth layers.',
			patch: {
				seed: 'grid-drift',
				seedLocked: true,
			},
		},
		{
			key: 'seed-live',
			label: 'Live Random',
			description: 'Unlock and reroll on demand.',
			patch: {
				seedLocked: false,
			},
		},
	],
};

export const EFFECT_PRESET_CATALOG: EffectPresetCatalog = {
	blur: [
		{
			key: 'blur-off',
			label: 'Off',
			description: 'Disable blur.',
			patch: {
				blurEnabled: false,
			},
		},
		{
			key: 'blur-small',
			label: 'Silk Haze',
			description: 'Light softness with crisp structure.',
			patch: {
				blurEnabled: true,
				blurStdDeviation: 42,
			},
		},
		{
			key: 'blur-medium',
			label: 'Studio Soft',
			description: 'Balanced diffusion for polished blends.',
			patch: {
				blurEnabled: true,
				blurStdDeviation: 78,
			},
		},
		{
			key: 'blur-large',
			label: 'Dream Fog',
			description: 'Heavy haze for atmospheric glow fields.',
			patch: {
				blurEnabled: true,
				blurStdDeviation: 128,
			},
		},
	],
	glow: [
		{
			key: 'glow-off',
			label: 'Off',
			description: 'Disable glow pass.',
			patch: {
				glowEnabled: false,
			},
		},
		{
			key: 'glow-small',
			label: 'Halo Veil',
			description: 'Subtle halo wrap around bright regions.',
			patch: {
				glowEnabled: true,
				glowStdDeviation: 76,
				glowIntensity: 1.6,
				glowBlendMode: 'screen',
			},
		},
		{
			key: 'glow-medium',
			label: 'Neon Lift',
			description: 'Balanced luminous lift for most scenes.',
			patch: {
				glowEnabled: true,
				glowStdDeviation: 110,
				glowIntensity: 2.7,
				glowBlendMode: 'overlay',
			},
		},
		{
			key: 'glow-large',
			label: 'Solar Bloom',
			description: 'Strong radiance with cinematic highlight spill.',
			patch: {
				glowEnabled: true,
				glowStdDeviation: 154,
				glowIntensity: 4.1,
				glowBlendMode: 'color-dodge',
			},
		},
	],
	noise: [
		{
			key: 'noise-off',
			label: 'Off',
			description: 'Disable all noise overlays.',
			patch: {
				noiseEnabled: false,
			},
		},
		{
			key: 'noise-small',
			label: 'Dust Kiss',
			description: 'Light analog texture with subtle grain.',
			patch: {
				noiseEnabled: true,
				noiseOpacity: 0.04,
				noiseFrequency: 0.9,
				coarseNoiseOpacity: 0.02,
				coarseNoiseFrequency: 0.06,
			},
		},
		{
			key: 'noise-medium',
			label: 'Film Texture',
			description: 'Balanced film-like grain profile.',
			patch: {
				noiseEnabled: true,
				noiseOpacity: 0.08,
				noiseFrequency: 1.1,
				coarseNoiseOpacity: 0.045,
				coarseNoiseFrequency: 0.1,
			},
		},
		{
			key: 'noise-large',
			label: 'Rough Grain',
			description: 'Pronounced texture for gritty surfaces.',
			patch: {
				noiseEnabled: true,
				noiseOpacity: 0.14,
				noiseFrequency: 1.45,
				coarseNoiseOpacity: 0.08,
				coarseNoiseFrequency: 0.16,
			},
		},
	],
	warp: [
		{
			key: 'warp-off',
			label: 'Off',
			description: 'Disable liquid warp distortion.',
			patch: {
				warpEnabled: false,
			},
		},
		{
			key: 'warp-small',
			label: 'Ripple Drift',
			description: 'Gentle wave motion through the field.',
			patch: {
				warpEnabled: true,
				warpAmount: 12,
				warpSpeed: 0.45,
				warpBaseFrequency: 0.004,
			},
		},
		{
			key: 'warp-medium',
			label: 'Liquid Fold',
			description: 'Balanced fluid distortion and flow.',
			patch: {
				warpEnabled: true,
				warpAmount: 22,
				warpSpeed: 0.82,
				warpBaseFrequency: 0.006,
			},
		},
		{
			key: 'warp-large',
			label: 'Storm Distort',
			description: 'High-energy warping with aggressive movement.',
			patch: {
				warpEnabled: true,
				warpAmount: 34,
				warpSpeed: 1.2,
				warpBaseFrequency: 0.009,
			},
		},
	],
	metaball: [
		{
			key: 'metaball-off',
			label: 'Off',
			description: 'Disable shape fusion.',
			patch: {
				metaballEnabled: false,
			},
		},
		{
			key: 'metaball-small',
			label: 'Soft Merge',
			description: 'Light fusion between close forms.',
			patch: {
				metaballEnabled: true,
				metaballBlur: 14,
				metaballThreshold: 0.72,
			},
		},
		{
			key: 'metaball-medium',
			label: 'Gel Fuse',
			description: 'Balanced gooey blending and cohesion.',
			patch: {
				metaballEnabled: true,
				metaballBlur: 22,
				metaballThreshold: 0.6,
			},
		},
		{
			key: 'metaball-large',
			label: 'Molten Merge',
			description: 'Heavy fusion for molten blob behavior.',
			patch: {
				metaballEnabled: true,
				metaballBlur: 30,
				metaballThreshold: 0.5,
			},
		},
	],
	bloom: [
		{
			key: 'bloom-off',
			label: 'Off',
			description: 'Disable bloom pass.',
			patch: {
				bloomEnabled: false,
			},
		},
		{
			key: 'bloom-small',
			label: 'Highlight Kiss',
			description: 'Subtle highlight blooming with restraint.',
			patch: {
				bloomEnabled: true,
				bloomThreshold: 0.68,
				bloomRadius: 28,
				bloomIntensity: 0.35,
			},
		},
		{
			key: 'bloom-medium',
			label: 'Lumen Bloom',
			description: 'Balanced cinematic glow spread.',
			patch: {
				bloomEnabled: true,
				bloomThreshold: 0.58,
				bloomRadius: 46,
				bloomIntensity: 0.75,
			},
		},
		{
			key: 'bloom-large',
			label: 'Radiant Burst',
			description: 'Aggressive bloom for intense brightness.',
			patch: {
				bloomEnabled: true,
				bloomThreshold: 0.45,
				bloomRadius: 68,
				bloomIntensity: 1.2,
			},
		},
	],
	posterize: [
		{
			key: 'posterize-off',
			label: 'Off',
			description: 'Disable posterize effect.',
			patch: {
				posterizeEnabled: false,
			},
		},
		{
			key: 'posterize-8-levels',
			label: 'Soft Bands',
			description: 'Subtle stepped tonality with smooth transitions.',
			patch: {
				posterizeEnabled: true,
				posterizeLevels: 8,
				posterizeOpacity: 0.22,
			},
		},
		{
			key: 'posterize-5-levels',
			label: 'Graphic Split',
			description: 'Balanced graphic segmentation.',
			patch: {
				posterizeEnabled: true,
				posterizeLevels: 5,
				posterizeOpacity: 0.38,
			},
		},
		{
			key: 'posterize-3-levels',
			label: 'Poster Punch',
			description: 'Strong stylized block transitions.',
			patch: {
				posterizeEnabled: true,
				posterizeLevels: 3,
				posterizeOpacity: 0.62,
			},
		},
	],
	caustic: [
		{
			key: 'caustic-off',
			label: 'Off',
			description: 'Disable caustic highlights.',
			patch: {
				causticEnabled: false,
			},
		},
		{
			key: 'caustic-small',
			label: 'Pool Ripple',
			description: 'Subtle water-like shimmer texture.',
			patch: {
				causticEnabled: true,
				causticIntensity: 0.18,
				causticScale: 0.014,
				causticSpeed: 0.35,
			},
		},
		{
			key: 'caustic-medium',
			label: 'Shimmer Field',
			description: 'Balanced animated refractive field.',
			patch: {
				causticEnabled: true,
				causticIntensity: 0.36,
				causticScale: 0.011,
				causticSpeed: 0.82,
			},
		},
		{
			key: 'caustic-large',
			label: 'Refractive Flash',
			description: 'Pronounced refractive sparkle and motion.',
			patch: {
				causticEnabled: true,
				causticIntensity: 0.56,
				causticScale: 0.008,
				causticSpeed: 1.3,
			},
		},
	],
	depth: [
		{
			key: 'depth-off',
			label: 'Off',
			description: 'Disable depth layering.',
			patch: {
				depthEnabled: false,
			},
		},
		{
			key: 'depth-small',
			label: 'Light Stack',
			description: 'Light depth layering with soft separation.',
			patch: {
				depthEnabled: true,
				depthLayers: 2,
				depthStrength: 0.32,
			},
		},
		{
			key: 'depth-medium',
			label: 'Layered Float',
			description: 'Balanced multi-layer parallax feel.',
			patch: {
				depthEnabled: true,
				depthLayers: 3,
				depthStrength: 0.58,
			},
		},
		{
			key: 'depth-large',
			label: 'Deep Stack',
			description: 'Strong depth separation and stack contrast.',
			patch: {
				depthEnabled: true,
				depthLayers: 5,
				depthStrength: 0.95,
			},
		},
	],
	fringe: [
		{
			key: 'fringe-off',
			label: 'Off',
			description: 'Disable chromatic fringe.',
			patch: {
				fringeEnabled: false,
			},
		},
		{
			key: 'fringe-small',
			label: 'Lens Hint',
			description: 'Light but visible RGB edge separation.',
			patch: {
				fringeEnabled: true,
				fringeAmount: 1.6,
			},
		},
		{
			key: 'fringe-medium',
			label: 'Split Edges',
			description: 'Clear chromatic edge split across forms.',
			patch: {
				fringeEnabled: true,
				fringeAmount: 3.4,
			},
		},
		{
			key: 'fringe-large',
			label: 'Prism Tear',
			description: 'Aggressive aberration with heavy prismatic split.',
			patch: {
				fringeEnabled: true,
				fringeAmount: 5.6,
			},
		},
	],
	sweep: [
		{
			key: 'sweep-off',
			label: 'Off',
			description: 'Disable light sweep.',
			patch: {
				sweepEnabled: false,
			},
		},
		{
			key: 'sweep-small',
			label: 'Soft Sweep',
			description: 'Slow soft sweep beam.',
			patch: {
				sweepEnabled: true,
				sweepIntensity: 0.14,
				sweepWidth: 0.3,
				sweepSpeed: 0.35,
				sweepAngle: -20,
			},
		},
		{
			key: 'sweep-medium',
			label: 'Studio Sweep',
			description: 'Balanced directional light pass.',
			patch: {
				sweepEnabled: true,
				sweepIntensity: 0.28,
				sweepWidth: 0.22,
				sweepSpeed: 0.75,
				sweepAngle: -28,
			},
		},
		{
			key: 'sweep-large',
			label: 'Laser Sweep',
			description: 'Bright fast moving directional beam.',
			patch: {
				sweepEnabled: true,
				sweepIntensity: 0.45,
				sweepWidth: 0.14,
				sweepSpeed: 1.2,
				sweepAngle: -34,
			},
		},
	],
	vignette: [
		{
			key: 'vignette-off',
			label: 'Off',
			description: 'Disable vignette darkening.',
			patch: {
				vignetteEnabled: false,
			},
		},
		{
			key: 'vignette-small',
			label: 'Soft Edges',
			description: 'Subtle edge darkening.',
			patch: {
				vignetteEnabled: true,
				vignetteAmount: 0.14,
				vignetteColor: '#040a16',
			},
		},
		{
			key: 'vignette-medium',
			label: 'Cinema Edge',
			description: 'Balanced cinematic vignette shape.',
			patch: {
				vignetteEnabled: true,
				vignetteAmount: 0.28,
				vignetteColor: '#040a16',
			},
		},
		{
			key: 'vignette-large',
			label: 'Noir Frame',
			description: 'Strong edge emphasis for moody scenes.',
			patch: {
				vignetteEnabled: true,
				vignetteAmount: 0.44,
				vignetteColor: '#030712',
			},
		},
	],
	paletteDrift: [
		{
			key: 'palette-drift-off',
			label: 'Off',
			description: 'Disable animated hue drift.',
			patch: {
				paletteDriftEnabled: false,
			},
		},
		{
			key: 'palette-drift-small',
			label: 'Slow Shift',
			description: 'Very gentle hue movement over time.',
			patch: {
				paletteDriftEnabled: true,
				paletteDriftSpeed: 0.12,
			},
		},
		{
			key: 'palette-drift-medium',
			label: 'Living Palette',
			description: 'Balanced evolving palette motion.',
			patch: {
				paletteDriftEnabled: true,
				paletteDriftSpeed: 0.28,
			},
		},
		{
			key: 'palette-drift-large',
			label: 'Chromaflux',
			description: 'Fast dynamic hue modulation.',
			patch: {
				paletteDriftEnabled: true,
				paletteDriftSpeed: 0.55,
			},
		},
	],
	hueRotate: [
		{
			key: 'hue-rotate-off',
			label: 'Off',
			description: 'Disable hue rotation.',
			patch: {
				hueRotateEnabled: false,
			},
		},
		{
			key: 'hue-rotate-dawn',
			label: 'Dawn Shift',
			description: 'Slow warm-cool rotation through the palette.',
			patch: {
				hueRotateEnabled: true,
				hueRotateDegrees: 24,
				hueRotateSpeed: 0.16,
			},
		},
		{
			key: 'hue-rotate-spectrum',
			label: 'Spectrum Loop',
			description: 'Balanced full-spectrum color orbit.',
			patch: {
				hueRotateEnabled: true,
				hueRotateDegrees: 110,
				hueRotateSpeed: 0.38,
			},
		},
		{
			key: 'hue-rotate-prism',
			label: 'Prism Pulse',
			description: 'Fast vivid hue motion for energetic scenes.',
			patch: {
				hueRotateEnabled: true,
				hueRotateDegrees: 210,
				hueRotateSpeed: 0.72,
			},
		},
	],
};

export const DEFAULT_PRESET_SELECTIONS: PresetSelectionState = {
	style: PRESET_CATALOG.style[0]?.key ?? '',
	layout: PRESET_CATALOG.layout[0]?.key ?? '',
	motion:
		PRESET_CATALOG.motion.find((entry) => entry.key === 'motion-balanced')
			?.key ??
		PRESET_CATALOG.motion[0]?.key ??
		'',
	palette: PRESET_CATALOG.palette[0]?.key ?? '',
	seed: PRESET_CATALOG.seed[0]?.key ?? '',
};

export const DEFAULT_EFFECT_PRESET_SELECTIONS: EffectPresetSelectionState = {
	blur: EFFECT_PRESET_CATALOG.blur[2]?.key ?? '',
	glow: EFFECT_PRESET_CATALOG.glow[0]?.key ?? '',
	noise: EFFECT_PRESET_CATALOG.noise[2]?.key ?? '',
	warp: EFFECT_PRESET_CATALOG.warp[0]?.key ?? '',
	metaball: EFFECT_PRESET_CATALOG.metaball[0]?.key ?? '',
	bloom: EFFECT_PRESET_CATALOG.bloom[0]?.key ?? '',
	posterize: EFFECT_PRESET_CATALOG.posterize[0]?.key ?? '',
	caustic: EFFECT_PRESET_CATALOG.caustic[0]?.key ?? '',
	depth: EFFECT_PRESET_CATALOG.depth[2]?.key ?? '',
	fringe: EFFECT_PRESET_CATALOG.fringe[0]?.key ?? '',
	sweep: EFFECT_PRESET_CATALOG.sweep[0]?.key ?? '',
	vignette: EFFECT_PRESET_CATALOG.vignette[2]?.key ?? '',
	paletteDrift: EFFECT_PRESET_CATALOG.paletteDrift[0]?.key ?? '',
	hueRotate: EFFECT_PRESET_CATALOG.hueRotate[0]?.key ?? '',
};
